Update all dependencies
mercari/tfnotify pull request #118
Opened 2022-07-19 10:04 UTC by baurmatt

## WHAT

Updated all dependencies

## WHY

Was building on may Apple M1.

```bash
$ go build
# golang.org/x/sys/unix
../../go/pkg/mod/golang.org/x/sys@v0.0.0-20200121082415-34d275377bf9/unix/syscall_darwin.1_13.go:25:3: //go:linkname must refer to declared function or variable
../../go/pkg/mod/golang.org/x/sys@v0.0.0-20200121082415-34d275377bf9/unix/zsyscall_darwin_arm64.1_13.go:27:3: //go:linkname must refer to declared function or variable
../../go/pkg/mod/golang.org/x/sys@v0.0.0-20200121082415-34d275377bf9/unix/zsyscall_darwin_arm64.1_13.go:40:3: //go:linkname must refer to declared function or variable
../../go/pkg/mod/golang.org/x/sys@v0.0.0-20200121082415-34d275377bf9/unix/zsyscall_darwin_arm64.go:28:3: //go:linkname must refer to declared function or variable
../../go/pkg/mod/golang.org/x/sys@v0.0.0-20200121082415-34d275377bf9/unix/zsyscall_darwin_arm64.go:43:3: //go:linkname must refer to declared function or variable
../../go/pkg/mod/golang.org/x/sys@v0.0.0-20200121082415-34d275377bf9/unix/zsyscall_darwin_arm64.go:59:3: //go:linkname must refer to declared function or variable
../../go/pkg/mod/golang.org/x/sys@v0.0.0-20200121082415-34d275377bf9/unix/zsyscall_darwin_arm64.go:75:3: //go:linkname must refer to declared function or variable
../../go/pkg/mod/golang.org/x/sys@v0.0.0-20200121082415-34d275377bf9/unix/zsyscall_darwin_arm64.go:90:3: //go:linkname must refer to declared function or variable
../../go/pkg/mod/golang.org/x/sys@v0.0.0-20200121082415-34d275377bf9/unix/zsyscall_darwin_arm64.go:105:3: //go:linkname must refer to declared function or variable
../../go/pkg/mod/golang.org/x/sys@v0.0.0-20200121082415-34d275377bf9/unix/zsyscall_darwin_arm64.go:121:3: //go:linkname must refer to declared function or variable
../../go/pkg/mod/golang.org/x/sys@v0.0.0-20200121082415-34d275377bf9/unix/zsyscall_darwin_arm64.go:121:3: too many errors
```

2022-07-19 23:24 UTC, drlau requested changes
Thanks for your contribution! Can you also update the mock GitLab API in `notifier/gitlab/gitlab_test.go`? `s/OptionFunc/RequestOptionFunc`

2022-07-20 05:32 UTC, baurmatt commented
Ah sorry, missed that! Done :)

2022-12-09 04:13 UTC, drlau commented on notifier/gitlab/client.go
>  	"os"
```suggestion
	"fmt"
	"os"
```

2022-12-09 04:30 UTC, drlau commented on notifier/gitlab/client.go
> +	"fmt"
```suggestion
```

2022-12-09 04:35 UTC, drlau approved these changes

2022-12-09 04:35 UTC, merged